### ISSUE TITLE
Time Tracker

### ISSUE THREAD

**Issue by coderix** [coderix/ProjectTime#2]
Start and stop of time track actions
- [x] New tab with empty view
- [x] Client selection
- [x] deactivate projects tab when no clients exist
- [x] deactivate time track tab when no projects exist
- [x] project selection
- [x] order of clients
- [x] order of projects
- [ ] read running task on start
- [ ] show duration of stopped task
- [ ] delete
- [ ] cancel
- [ ] edit
- [ ] Styling of Buttons
